### ISSUE TITLE
Help needed to convert dart code into java

### ISSUE THREAD

**Issue by im-ankitjais** [im-ankitjais/Dart-to-Java#1]
Kindly go into main.dart and see the code. It uses the post method. Go and check server.py if needed.
Go to project-av.onrender.com to see what i wanted to do in my android app which i'm building using java.

**Comment by IamShivamJaiswal** [comment]
I'll take

**Comment by abhinavsp0730** [comment]
@IamShivamJaiswal  Sure just mail me the code of equivalent java code
In abhinavsp0730@gmail.com.

**Comment by im-ankitjais** [comment]
Thanks for showing interest @IamShivamJaiswal . Create a new .java file that works similar to that Dart code.

**Comment by IamShivamJaiswal** [comment]
check the PR #2
